spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  secret: 8a6873a9-021e-4747-bf4f-ea82449852a8
  expiration: 999999